project_id = "pprjjmbxiurwpaoncoqv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
external_url = "https://pprjjmbxiurwpaoncoqv.supabase.co"

[functions.process-pdf]
verify_jwt = false

[functions.process-url]
verify_jwt = false

[functions.generate-cards]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324