// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pprjjmbxiurwpaoncoqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwcmpqbWJ4aXVyd3Bhb25jb3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNDE1MTMsImV4cCI6MjA3MDcxNzUxM30.WpKt3brquw3QaofTNE-OvHXRr9zZ71tpx-u1RGyImHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});